wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.7
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.0
change_nans:
  desc: null
  value:
    value: 0
clean_features:
  desc: null
  value:
    exceptions:
    - Action
dataset_name:
  desc: null
  value: ''
id:
  desc: null
  value: ''
labels:
  desc: null
  value: target
merge:
  desc: null
  value:
    group_names:
    - 3sn6
    - 4lde
    - 5jqh
    groups:
    - - 3sn6-ant
      - 3sn6-ag
    - - 4lde-ant
      - 4lde-ag
    - - 5jqh-ant
      - 5jqh-ag
    merge_all: true
    merge_all_name: merged-3sn6-4lde-5jqh
model_hyperparameters:
  desc: null
  value:
    criterion: gini
    max_depth: 3
    max_features: auto
    n_estimators: 100
project_name:
  desc: null
  value: test_optim
remove_features:
  desc: null
  value:
    search_params:
    - Clash
    - Proximal
rename_features:
  desc: null
  value:
    renames:
      action: target
run_name:
  desc: null
  value: test run
src:
  desc: null
  value: ''
test_size:
  desc: null
  value: 0.1
