wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.7
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.3
models:
  desc: null
  value:
    class_names:
    - ant
    - ag
    criterion: gini
    k_folds: 10
    learning_curve: true
    max_depth: null
    max_features: null
    n_jobs: 4
    scorer: Matthews Correlation Coefficient
    splitter: best
setup:
  desc: null
  value:
    active: true
    dataset: merged-B2in-Z-R
    dtype: int64
    file: decision_tree
    id: decision_tree_1
    log: true
    model_name: CART Model
    project: test split
    run_name: CART - Merged-B2in-Z-R
    save_model: true
    shuffle: true
    wandb_key: null
    y_labels: target
