program: Balanced_AdaBoost_sweep.py
method: bayes
metric:
  goal: maximize
  name: Mean
name: AdaBoost Sweep
parameters:
  algorithm:
    distribution: categorical
    values:
    - SAMME
    - SAMME.R
  learning_rate:
    distribution: uniform
    max: 1
    min: 0
  max_depth_base_estimator:
    distribution: int_uniform
    max: 10
    min: 1
  n_estimators:
    distribution: int_uniform
    max: 1000
    min: 10
