program: unfiltered_RFC_sweep.py
method: bayes
metric:
    name: Mean
    goal: maximize
parameters:
    n_estimators:
        distribution: int_uniform
        max: 4000
        min: 2000

    max_features:
        distribution: int_uniform
        max: 100
        min: 1

    max_depth:
        distribution: int_uniform
        max: 4000
        min: 2000

    min_samples_split:
        distribution: int_uniform
        max: 150
        min: 2

    min_samples_leaf:
        distribution: int_uniform
        max: 100
        min: 2

    max_leaf_nodes:
        distribution: int_uniform
        max: 4000
        min: 2000