program: unfiltered_RFC_sweep.py
method: bayes
metric:
    name: Mean
    goal: maximize
parameters:
    n_estimators:
        distribution: int_uniform
        max: 8000
        min: 1

    max_features:
        distribution: int_uniform
        max: 22
        min: 2

    min_samples_split:
        distribution: int_uniform
        max: 10
        min: 2

    min_samples_leaf:
        distribution: int_uniform
        max: 3
        min: 2
